# Generated by Django 3.2.7 on 2024-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20241115_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carimage',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=255),
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
